### ISSUE TITLE
todo list for the admob adapter

### ISSUE THREAD

**Issue by jjhesk** [cymcsg/UltimateRecyclerView#104]
- [x] fix add and remove data from the admob list.

- [x] research for issue [inconsistency viewholder](https://www.google.com.hk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=java.lang.IndexOutOfBoundsException%3A%20Inconsistency%20detected.%20Invalid%20view%20holder%20adapter%20positionViewHolder)
- [x] fixed the screen size issue related to the image ad from google admob

**Comment by jjhesk** [comment]
@cymcsg  lets add this on the 0.4 milestone
